on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: dnonakolesax/hw2:latest
    steps:
    - uses: actions/checkout@v2
    - run: make build

  test:
    runs-on: ubuntu-latest
    container: dnonakolesax/hw2:latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - run: make build && make test  
  coverage:
    runs-on: ubuntu-latest
    container: dnonakolesax/hw2:latests
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - run: make build && make coverage
    - uses: actions/upload-artifact@v2